apiVersion: apps/v1
kind: Deployment
metadata:
  name: contagem-api-deployment
  labels:
    app: contagem-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: contagem-api
  template:
    metadata:
      labels:
        app: contagem-api
    spec:
      containers:
      - name: contagem-api
        image: renatogroffe/apicontagemk8s:latest
        env:
          - name: TesteAmbiente
            value: Utilizando o Azure Kubernetes Service (AKS) com deployment via GitHub Actions
        ports:
        - containerPort: 80